---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-casc-secret
  namespace: jenkins
  labels:
    service_name: jenkins
    service_group: tools
type: Opaque
data:
  google-oauth2-clientId: "<YOUR GOOGLE CLIENTID> | BASE64"
  google-oauth2-clientSecret: "<YOUR GOOGLE SECRET> | BASE64"
